name: Commit, Push, and PR Workflow

on:
  push:             # Triggers on any push (commit)
    branches:
      - '**'        # all branches
  pull_request:     # Triggers on PR creation, update, reopen
    branches:
      - '**'

jobs:
  on-commit-push-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show event name
        run: echo "Triggered by: ${{ github.event_name }}"

      - name: List files in the repo
        run: ls -al
